# The default Gemini model to use for summaries.
# This can be overridden by the --model command-line flag.
gemini_model = "gemini-2.0-flash"

# Your Gemini API key.
# If this is empty, the application will check the GEMINI_API_KEY environment variable.
# If neither is set, you will be prompted to enter a key on startup.
gemini_api_key = ""

# Set to false to disable the startup prompt for the API key.
prompt_for_api_key = true

# Path to a custom prompt template file.
# If set, this file will be used for generating AI summaries.
# This can be overridden by the --prompt command-line flag.
custom_prompt_path = ""

# Default language for the AI summary.
# Can be overridden by the --lang command-line flag.
lang = "english"